[2023-01-16T01:55:57.377+0000] {taskinstance.py:1159} INFO - Dependencies not met for <TaskInstance: user_processing.create_table scheduled__2023-01-12T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2023-01-16T01:55:57.414+0000] {local_task_job.py:103} INFO - Task is not able to be run
